apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-via-jenkins
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - nodePort: 322232
      port: 80
      Protocol: TCP
      targetPort: 80
